[build]

  # Specifies the command to build the app
  command = "npm run build --prefix client"

  # Specifies the directory to deploy the app from
  publish = "/client/build"

[[redirects]]
  # Redirects all URLs to the index.html file
  from = "/*"
  to = "/client/public/index.html"
  status = 200
