[build]

  # Specifies the command to build the app
  command = "cd client && npm run build"

  # Specifies the directory to deploy the app from
  publish = "client/build"

  base = "client"
  
[[redirects]]
  # Redirects all URLs to the index.html file
  from = "/*"
  to = "/client/public/index.html"
  status = 200
